ARG RUST_VERSION=1.92

ARG APP_NAME=sentinel_orchestrator

FROM docker.io/library/rust:${RUST_VERSION}-alpine AS build

ARG APP_NAME
WORKDIR /app

ENV OPENSSL_STATIC=1

RUN apk add --no-cache clang lld musl-dev git pkgconfig openssl-dev openssl-libs-static

COPY Cargo.toml Cargo.lock ./
COPY crates/ crates/

RUN --mount=type=cache,target=/app/target/ \
    --mount=type=cache,target=/usr/local/cargo/git/db \
    --mount=type=cache,target=/usr/local/cargo/registry/ \
    cargo build --locked --release --bin sentinel_orchestrator && \
    cp ./target/release/$APP_NAME /bin/sentinel_orchestrator

FROM docker.io/library/alpine:3.18 AS final

RUN apk add --no-cache ca-certificates

ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    appuser

RUN mkdir -p /app/output/ndvi && chown -R appuser /app
USER appuser

COPY --from=build /bin/sentinel_orchestrator /bin/

CMD ["/bin/sentinel_orchestrator"]